move old tests to old_tests and instruct pytest to ignore them when running ============================= test session starts ============================== platform linux -- Python 3.7.6, pytest-6.0.0rc1, py-1.9.0, pluggy-0.13.1 rootdir: /home/ovs72384/Projects/cuda-slic collected 9 items
tests_unit/test_slic3d.py ........F                                      [100%]

=================================== FAILURES ===================================
___________________________ test_stress_test_slic3d ____________________________

    def test_stress_test_slic3d():
        lengths = range(100, 200, 3)
        for i in range(len(lengths)):
            n_segments = lengths[i]**3/10**3
            blob = data.binary_blobs(length=lengths[i], n_dim=3, seed=2)
            blob = np.float32(blob)
>           slic3d(blob, n_segments=n_segments, compactness=2)

tests_unit/test_slic3d.py:74:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
survos2/improc/utils.py:565: in wrapper
    result = func(*DM.sources, **kwargs)
survos2/improc/cuda.py:39: in wrapper
    r = func(*args, **kwargs)
survos2/improc/regions/slic.py:91: in slic3d
    r = ccl3d(labels_gpu, remap=True)
survos2/improc/utils.py:565: in wrapper
    result = func(*DM.sources, **kwargs)
survos2/improc/cuda.py:39: in wrapper
    r = func(*args, **kwargs)
survos2/improc/regions/ccl.py:30: in ccl3d
    _mod_conv = SourceModule(f.read())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pycuda.compiler.SourceModule object at 0x7fea918ed9d0>
source = '/*\n * Connected Components in the GPU\n * Paper Source: An Optimized Union-Find Algorithm for Connected\n *         ...\n    if ( p.z < shape.z && p.y < shape.y && p.x < shape.x ) {\n        labels[gidx] = find(labels, gidx);\n    }\n}\n'
nvcc = 'nvcc', options = None, keep = False, no_extern_c = False, arch = None
code = None, cache_dir = None, include_dirs = []

    def __init__(self, source, nvcc="nvcc", options=None, keep=False,
            no_extern_c=False, arch=None, code=None, cache_dir=None,
            include_dirs=[]):
        self._check_arch(arch)

        cubin = compile(source, nvcc, options, keep, no_extern_c,
                arch, code, cache_dir, include_dirs)

        from pycuda.driver import module_from_buffer
>       self.module = module_from_buffer(cubin)
E       pycuda._driver.LogicError: cuModuleLoadDataEx failed: an illegal memory access was encountered -

/scratch/ovs72384/anaconda3/envs/gpu-slic/lib/python3.7/site-packages/pycuda/compiler.py:294: LogicError
=============================== warnings summary ===============================
/scratch/ovs72384/anaconda3/envs/gpu-slic/lib/python3.7/site-packages/falcon/util/__init__.py:29
  /scratch/ovs72384/anaconda3/envs/gpu-slic/lib/python3.7/site-packages/falcon/util/__init__.py:29: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
    from falcon.util import structures

tests_unit/test_slic3d.py: 74 warnings
  /scratch/ovs72384/anaconda3/envs/gpu-slic/lib/python3.7/site-packages/pycuda/gpuarray.py:183: DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
    s = np.asscalar(s)

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED tests_unit/test_slic3d.py::test_stress_test_slic3d - pycuda._driver.Lo...
================== 1 failed, 8 passed, 75 warnings in 15.23s ===================